apiVersion: v1
kind: Service
metadata:
  namespace: anotherclass-212
  name: api-tester-2121
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-2121
    version: 1.0.0
    managed-by: kubectl
spec:
  selector:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-2121
  ports:
    - port: 80
      targetPort: http
      nodePort: 32121
  type: NodePort
