apiVersion: v1
kind: Service
metadata:
  namespace: anotherclass-221
  name: api-tester-2214
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-2214
    version: 1.0.0
    managed-by: kubectl
spec:
  selector:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-2214
    blue-green-no: "1"
  ports:
    - port: 80
      targetPort: http
      nodePort: 32214
  type: NodePort
