apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-tester.fullname" . }}-postgresql
  labels:
    {{- include "api-tester.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.secret.data.postgresql | nindent 2 }}
