apiVersion: v1
kind: ConfigMap
metadata:
  namespace: anotherclass-221
  name: api-tester-properties
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester
    version: 1.0.0
    managed-by: kubectl
data:
  spring_profiles_active: "dev"
  application_role: "ALL"
  postgresql_filepath: "/usr/src/myapp/datasource/postgresql-info.yaml"