apiVersion: v1
kind: Service
metadata:
  namespace: anotherclass-222
  name: api-tester-2221
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-2221
    version: 1.0.0
    managed-by: kubectl
spec:
  selector:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-2221
  ports:
    - port: 80
      targetPort: http
      nodePort: 32221
  type: NodePort
